export const Constants = {

  // CONTEXT_PATH: 'http://192.168.0.102:8090/',
  CONTEXT_PATH: 'http://localhost:8090/',

  // CONFIG MESSAGE**//
  MSG_REQUIRED_ERROR: '${FieldName} is required.',
  MSG_NO_FOUND_DATA: 'No data found',
  MSG_DUPLICATED: '${Value} is duplicated.',
  MSG_CREATE_SUCCESSFUL: 'Create successful',
  MSG_CREATE_FAIL: 'Create fail',
  MSG_UPDATE_SUCCESSFUL: 'Update successful',
  MSG_UPDATE_FAIL: 'Update fail',
  MSG_DETELE_SUCCESSFUL: 'Delete successful',
  MSG_DETELE_FAIL: 'Delete fail',
  MSG_EXPORT_SUCCESSFUL: 'Export successful',
  MSG_EXPORT_FAIL: 'Export fail',
  MSG_SUCCESS: 'success',
  MSG_WARN: 'warn',
  MSG_DO_NOT_EXIST: '${Label} does not exist.',
  SUCCESS: 'Success',
  FAIL: 'Fail',
  QUEUED: 'Queued',
  MSG_CREATE_LIMIT: 'Cannot create new ${FieldName} because it reaches the limitation of application.',
  MSG_ERROR: 'error',
  MSG_SERVER_ERROR: 'There is problem with server. Please try again.',
  MSG_CONFIRM_DELETE: 'Are you sure you want to delete this item?',
  PAGE_SIZE: 5,
  LIFE_TOAST: 3000,
  LIMIT_SIZE: 1000,
  TIME_CALL_API: 30000,
  SIZE_LIST: [5, 20, 50, 100, 200],
  PAGE_DEFAULT: 1,
  TRUE: 1,
  FALSE: 0,
  DATE_FORMAT: 'dd/MM/yyyy',
  USERNAME_EXIST: 'USERNAME IS EXIST'
};
